spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=utf-8
    username: root
    password: ms.com@483701
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ms.entity
